// app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Importa la configuración de FontAwesome
import "@/utils/fontawesome";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { TokenProvider } from "@/context/TokenContext/TokenContext";
import { UserProvider } from "@/context/UserContext/UserContext";
import Wrapper from "@/components/Wrapper/Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Mercadito",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TokenProvider>
          <UserProvider>
            <Header />
            <Wrapper>{children}</Wrapper>
            <Footer />
          </UserProvider>
        </TokenProvider>
      </body>
    </html>
  );
}
